# Generated by Django 3.2.6 on 2021-08-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
